### ISSUE TITLE
shaped-config:  New Characters > Roll Options > Roll 2 does not work as expected.

### ISSUE THREAD

**Issue by beeke01** [symposion/roll20-shaped-scripts#115]
1)  Run !shaped-config
2)  Navigate to New Characters > Roll Options and change to a Roll 2 value.
3)  Drop a new token on the map, select it, then use !shaped-import-monster to add a new monster.
4)  Open the character sheet and initiate the import.
5)  Validate that Roll 2 is never set.

**Comment by Brunhine** [comment]
Actually it looks like none of the roll options work for new characters.

I have validate that we are indeed sending an attribute set for roll_setting, but it appears to be showing up as @{roll_1} regardless of what we send

**Comment by Brunhine** [comment]
Upon further investigation, this appears to be an issue with the sheet itself.

The sheet is setting some defaults when it is opened for the first time. One of them happens to be setting the roll option to @{roll_1}.

Lucian is pushing a change Kryx to resolve this.
