### ISSUE TITLE
shaped-abilities enhancement for traits

### ISSUE THREAD

**Issue by beeke01** [symposion/roll20-shaped-scripts#116]
Just as you allow !shaped-abilities --Fireball to add the fireball spell as a token action, it would be nice to have this feature for traits as well.

For example a barbarian could then do !shaped-abilities --Rage to add a Rage token action.

**Comment by symposion** [comment]
Well, you can do !shaped-abilities --traits and then just delete any ones you don't want. The reason I added the special case for spells is because spellcasters tend to have a *lot* of spells, so adding all of them is probably not a good idea. But with traits there don't tend to be as many.

**Comment by beeke01** [comment]
This is currently the workflow that I use now.  After fixing up 6 PC sheets with the new changes I found myself wanting only 1-2 traits, sometimes out of quite a few particularly for the pure melee classes (Fighter, Barbarian), so just a suggestion, but if you don't feel it is worth the time investment I can agree with it :)
