### ISSUE TITLE
[shaped-at] passing id only works if something (anything) is selected

### ISSUE THREAD

**Issue by beeke01** [symposion/roll20-shaped-scripts#117]
Using !shaped-at --advantage --id <characterId> will still fail with the following error if nothing is selected:

"5eShapedCompanion 1462201799625 ERROR : Error: Error: Wrong number of objects of type [character] selected, should be between 1 and Infinity"

Realistically you should be able to run this command without having anything selected.

**Comment by Brunhine** [comment]
yep, completely missed this last night, my bad. Will issue a fix shortly.
