### ISSUE TITLE
[shaped-scripts] Auto-decrement spell slots

### ISSUE THREAD

**Issue by symposion** [symposion/roll20-shaped-scripts#16]
_From @symposion on April 3, 2016 10:18_

Decrement spell slots on cast
- Output list of available slots after each cast - ideally should use something from the sheet

_Copied from original issue: symposion/roll20-api-scripts#45_

**Comment by symposion** [comment]
_From @Brunhine on April 14, 2016 3:13_

I think the remaining slots output would be best executed by the sheet in
the same way that ammo is done. For consistency's sake.

**Comment by symposion** [comment]
>I think the remaining slots output would be best executed by the sheet in
>the same way that ammo is done. For consistency's sake.

Agreed, that was how i thought it would work. I mentioned to Mark about making the "Spell Slots" text clickable on the sheet to output the remaining slots, and we could then call this sheet roll to output the information. I seem to remember he was up for that idea, so you could drop him a note and ask about it.

**Comment by Brunhine** [comment]
Does this also decrement warlock spell slots?

**Comment by symposion** [comment]
No, not at the moment. TBH it's a fairly limited implementation. I think the whole idea of responding to the sheet spell output is slightly flawed to be honest, because there are so many restrictions that really need to be applied *before* you get to casting the spell.

I wrote a complex and nearly complete spellbook implementation for the old sheet that took all this stuff into account - rituals, different casting levels, warlock slots etc It displayed different chat window buttons depending on what you had prepared and what slots you had available, and pre-configured the buttons to cast at the optimal level, only prompting for a different level if there was a useful reason to do so.

Kryx wants to have a spellbook implementation as part of the sheet, so if I was going to reimplement this it would need to be in the sheetworkers rather than the companion script. I think it's were the effort would most usefully be focused because an after-the-fact spell-slot decrementer is  always going to be quite limited.

That said, adding warlock slots is probably worthwhile, particularly for the single class scenario where it's relatively straightforward. Also, judging by the comment on the forum thread, I think it probably breaks for warlock slots at the moment :-(

**Comment by symposion** [comment]
This implementation has too many problems, disabled for the moment
