### ISSUE TITLE
Implement security checks and send messages to the appropriate people

### ISSUE THREAD

**Issue by symposion** [symposion/roll20-shaped-scripts#165]
At the moment the script has no checks on who can perform different operations, and sends most of its messages to the GM directly. I need to add some restrictions that prevent people from modifying tokens they don't control, and then I need to ensure that system messages get reported to the player who issued the command.

Status messages like those from advantage tracker and the spell slots stuff should still go publicly to everyone

**Comment by mlenser** [comment]
If you're going to add security please ensure players can use the script with permission from the gm. I'm fine with my players having access.

**Comment by symposion** [comment]
I'd assumed that every player would have the ability to do script things that affect characters and tokens that they control; what I was going to restrict was players having the ability to modify things they don't control, and to import new monsters into the game. Do you want players to be able to control everything?

**Comment by mlenser** [comment]
Just tokens in their control is fine by me.
