### ISSUE TITLE
[shaped-scripts] Long/short rest commands

### ISSUE THREAD

**Issue by symposion** [symposion/roll20-shaped-scripts#17]
_From @symposion on April 3, 2016 10:16_

API commands for long/short rest. These would reset all spell slots and class feature use values back to their maxima + also do the appropriate things for HD.

_Copied from original issue: symposion/roll20-api-scripts#44_

**Comment by Brunhine** [comment]
Starting work on this

**Comment by Brunhine** [comment]
Just to make sure I am not forgetting anything:

Short Rest:
- short rest traits to max
- warlock spell slots to max

Long Rest:
- all of short rest
- HP to max
- spell slots to max
- regain half of max hit die

Missing anything?

**Comment by symposion** [comment]
Apparently there's a common houserule whereby a long rest recovers all HD and no HP. Might be nice to provide an option to support this.

**Comment by symposion** [comment]
Might also be worth thinking about the variants in the DMG p266-7

**Comment by symposion** [comment]
Have just been playing with this - I think it needs some chat feedback so that people know it has actually done something...

**Comment by Brunhine** [comment]
OK... That could be done.

Should it whisper the GM, whisper the player, or be public for all?

**Comment by Brunhine** [comment]
> Apparently there's a common houserule whereby a long rest recovers all HD and no HP. Might be nice to provide an option to support this.

> Might also be worth thinking about the variants in the DMG p266-7

I can look at adding these later. I think that there are some other things. specifically #75 that are higher priority than adding houserules and variants personally.

**Comment by symposion** [comment]
> Should it whisper the GM, whisper the player, or be public for all?
I think rests should be public for all - I can't really see any argument for keeping that private, can you?

Agreed about the houserules.

**Comment by Brunhine** [comment]
I talked to Kryx. He is going to be putting 2 buttons on the sheets.

Based off this, I have come up with this output:

![image](https://cloud.githubusercontent.com/assets/828357/14799869/6cc64100-0af3-11e6-91bf-b5fd9ad55673.png)

![image](https://cloud.githubusercontent.com/assets/828357/14799882/7bb59a12-0af3-11e6-8a16-e589ff68c0e0.png)
