### ISSUE TITLE
Spell components not imported properly with translations

### ISSUE THREAD

**Issue by mlenser** [symposion/roll20-shaped-scripts#177]
Hey Lucian.

I'm getting "COMPONENTS_V_S_M_M" when importing planar binding for example. That has:

"components": {
        "verbal": true,
        "somatic": true,
        "material": true,
        "materialMaterial": "A jewel worth at least 1,000 gp, which the spell consumes",
        "materialCost": 1000
      },

**Comment by symposion** [comment]
Hmm, interesting. I will take a look this afternoon.
