### ISSUE TITLE
shaped-support - Roll2 configuration is not working properly on import

### ISSUE THREAD

**Issue by beeke01** [symposion/roll20-shaped-scripts#222]
In 4.4.4 - When you import a new monster while the default roll option is set to Roll2, it fails to set Roll2 properly.

**Comment by symposion** [comment]
Hi,

I've just tried this and I can't reproduce. Can you try with the latest sheet and script again?

**Comment by beeke01** [comment]
I apologize for taking so long to get back.  This should be closed, it must have been something on my end or a temporary mismatch between sheet/script.
