### ISSUE TITLE
shaped-support - spell import size imports as normal, but outputs as big on new import

### ISSUE THREAD

**Issue by beeke01** [symposion/roll20-shaped-scripts#223]
1) !shaped-config - ensure that spell output is set to normal
2) !shaped-import-monster --archmage
3) open the sheet and complete the import
4) switch to the configuration tab and click the spell macro, instead of normal size, it will output as big

**Comment by symposion** [comment]
Ok, so this is working as expected in the script, but the problem is that the sheetworkers that change the text size aren't being triggered because the attribute is being set by the script before the sheet opens. I will chat to Mark about possibly checking this on sheet opening.
