### ISSUE TITLE
Split config menu into sections that fit into 600px

### ISSUE THREAD

**Issue by symposion** [symposion/roll20-shaped-scripts#24]
If you have to scroll up in the chat window to click the buttons in a part of the config UI, you don't see the refresh after you push the button, since the chat only auto-scrolls if you are already at the bottom. Combined with the fact that there are no visual affordances for pushing buttons in the chat, this makes it feel like nothing is happening, which could be very confusing for new users. We  should split the menu into chunks that fit in 600px so most users have a fighting chance of seeing the whole thing without scrolling back.

**Comment by Brunhine** [comment]
This has already been on my focus. 

As more features get added, I will need to have more top levels menus I think.

**Comment by Brunhine** [comment]
at this time the only menu that is taller than 600px is the tokens menu. Will adjust that
