### ISSUE TITLE
--as option for monsters and spells

### ISSUE THREAD

**Issue by symposion** [symposion/roll20-shaped-scripts#255]

**Comment by mlenser** [comment]
+1
It is troublesome to import a creature and then change its name everywhere.

**Comment by symposion** [comment]
Ok, so I've found a different way to deal with #261, so I've applied this only to monsters for the moment. I'm not sure I really see a particular use case for renaming spells on import right now - seems like an edge case and it wouldn't really save a huge amount of time in 99% of cases
