### ISSUE TITLE
Long resting should reset traits with a recharge of "X/Day"

### ISSUE THREAD

**Issue by mlenser** [symposion/roll20-shaped-scripts#264]
Currently Long resting only resets traits with "long" in their recharge. This should cover all cases of "X/Day" such as "1/Day", "3/Day", etc as well as "Recharges after a Short or Long Rest" and "Recharges after a Long Rest".

I'm going to use translations so you can look for "RECHARGE_X_DAY" or "RECHARGE_AFTER_SHORT_OR_LONG_REST" or "RECHARGE_AFTER_LONG_REST" as the values.

**Comment by mlenser** [comment]
fix for 8.0.0 please

**Comment by symposion** [comment]
I've got a fix lined up for this, but I'm waiting on the application of this system to the various other sections before finalising. For the record, the things I'm waiting on:

- current/remaining count for legendary actions (only have the max at the moment)
- Recharge condition for PC attacks
- Recharge condition for PC armor
- Uses for NPC actions
- Uses for NPC reactions
