### ISSUE TITLE
Create passive perception attribute for new characters

### ISSUE THREAD

**Issue by symposion** [symposion/roll20-shaped-scripts#27]

**Comment by Brunhine** [comment]
Is passive perception supported by the sheet?

**Comment by symposion** [comment]
Not yet, I know Mark has it on his todo list but i'm not sure how he's intending to implement. I somewhat disagree with Mark's choice to make the base skills into repeating items - I think the use case for completely redefining the skill list is a tiny edge case - and the consequence is that nothing outside of the sheet can reference skills by name without having all sorts of  javascript  jiggery-pokery in between. E.g. I want passive perception in a bubble on my tokens - only possible with a static attribute, not a repeating one. I'm not sure how he intends to implement passive perception, but my idea in the meantime was just to create a static attribute "passive_perception" that referenced the dynamic one with 10 + @{repeating_skills_2345234526_bonus} or whatever it's called. I'll probably remove it if Mark gets round to adding a statically named passive_perception attribute that is updated using sheet workers.

**Comment by symposion** [comment]
Ok, after discussion with Mark, I'm not going to do this in the script - he will provide something in the sheet and then if i need more I will do it separately for my own campaign.
