### ISSUE TITLE
Error when version 1.0.0 loads

### ISSUE THREAD

**Issue by DarokinB** [symposion/roll20-shaped-scripts#288]
I just pulled the raw of the spell data and when loaded it, and got an error: "SyntaxError: Unexpected token :"

I'm looking for the bug, it's likely a typo somewhere, but haven't found it yet. (sorry posted it originally in the wrong place)

**Comment by symposion** [comment]
Hi Darokin,

So I'm guessing that maybe you're someone who has reported an issue on the Roll20 forum - can't be sure because your username is different here. The error that you're seeing is almost certainly a result of something going wrong when you copy-pasted one of the files into the API script pane. Can you try the following please:

1.  Delete and repaste from github the latest 5.0.0 companion script
2. Delete and repaste from github the latest spells file

When doing so, please be absolutely sure that a) you've deleted all the previous text and b) you've copied all the text from the github window. Using Ctrl-A to select all of the text in both cases will ensure that you don't make any mistakes here.

If this doesn't work, please try disabling all other scripts in your campaign to make sure that the problem hasn't come from another script somewhere... and if that doesn't work, then PM me a campaign invite and I'll take a look.... but please only do that if you are *really* sure you've checked all the above carefully, because, as I say, this is almost *always* a copy-paste problem.

Cheers

If that doe

**Comment by DarokinB** [comment]
Hi Lycian,
I copied and pasted the spell data file, from the RAW, and pasted it into the spell data script, after completely clearing it. It's definitely the spell data that is the problem. I disabled the spell data file and the error went away.
I can try deleting the script and creating a new one to see if that sieves it, but I have never had that work before.
Josh
-------- Original message --------From: Lucian H <notifications@github.com> Date: 2/4/17  3:17 PM  (GMT-05:00) To: symposion/roll20-shaped-scripts <roll20-shaped-scripts@noreply.github.com> Cc: DarokinB <darokinb@aol.com>, Author <author@noreply.github.com> Subject: Re: [symposion/roll20-shaped-scripts] Error when version 1.0.0 loads
  (#288) 
Hi Darokin,
So I'm guessing that maybe you're someone who has reported an issue on the Roll20 forum - can't be sure because your username is different here. The error that you're seeing is almost certainly a result of something going wrong when you copy-pasted one of the files into the API script pane. Can you try the following please:

Delete and repaste from github the latest 5.0.0 companion script
Delete and repaste from github the latest spells file

When doing so, please be absolutely sure that a) you've deleted all the previous text and b) you've copied all the text from the github window. Using Ctrl-A to select all of the text in both cases will ensure that you don't make any mistakes here.
If this doesn't work, please try disabling all other scripts in your campaign to make sure that the problem hasn't come from another script somewhere... and if that doesn't work, then PM me a campaign invite and I'll take a look.... but please only do that if you are really sure you've checked all the above carefully, because, as I say, this is almost always a copy-paste problem.
Cheers
If that doe

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/symposion/roll20-shaped-scripts","title":"symposion/roll20-shaped-scripts","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/symposion/roll20-shaped-scripts"}},"updates":{"snippets":[{"icon":"PERSON","message":"@symposion in #288: Hi Darokin,\r\n\r\nSo I'm guessing that maybe you're someone who has reported an issue on the Roll20 forum - can't be sure because your username is different here. The error that you're seeing is almost certainly a result of something going wrong when you copy-pasted one of the files into the API script pane. Can you try the following please:\r\n\r\n1.  Delete and repaste from github the latest 5.0.0 companion script\r\n2. Delete and repaste from github the latest spells file\r\n\r\nWhen doing so, please be absolutely sure that a) you've deleted all the previous text and b) you've copied all the text from the github window. Using Ctrl-A to select all of the text in both cases will ensure that you don't make any mistakes here.\r\n\r\nIf this doesn't work, please try disabling all other scripts in your campaign to make sure that the problem hasn't come from another script somewhere... and if that doesn't work, then PM me a campaign invite and I'll take a look.... but please only do that if you are *really* sure you've checked all the above carefully, because, as I say, this is almost *always* a copy-paste problem.\r\n\r\nCheers\r\n\r\nIf that doe"}],"action":{"name":"View Issue","url":"https://github.com/symposion/roll20-shaped-scripts/issues/288#issuecomment-277473857"}}}

**Comment by symposion** [comment]
Hi Josh, 
Where exactly are you getting this spellData from? I've just pasted the data in again to my own campaign to check and it works fine.

**Comment by DarokinB** [comment]
From here: https://raw.githubusercontent.com/mlenser/roll20/master/data/spellSourceFiles/spellData.json

**Comment by symposion** [comment]
Hey,

You're pasting in the wrong file. You want https://raw.githubusercontent.com/mlenser/roll20/master/data/5e-spells.js . You should ignore all the .json files - they are not for use by end users really, they're just source files to generate the .js
