### ISSUE TITLE
Error when importing from statblock

### ISSUE THREAD

**Issue by mlenser** [symposion/roll20-shaped-scripts#297]
"5eShapedCompanion 1487018540899 ERROR : SyntaxError: Expected \"(\", \".\", \"[\", \"abs(\", \"ceil(\", \"d\", \"floor(\", \"round(\", \"t\", \"{\", [ |\\t], [+|\\-] or [0-9] but end of input found."
"5eShapedCompanion 1487018540900 ERROR : undefined"

Marrow
Medium humanoid (goblinoid), neutral evil
Armor Class 16
Hit Points 67 (9d8 + 27)
Speed 30 ft.
STR
12 (+1)
DEX
16 (+3)
CON
16 (+3)
INT
10 (+0)
WIS
8 (–1)
CHA
18 (+4)
Skills Arcana +4, Influence +6, Medicine +1, Perception +3, Stealth +5
Senses darkvision 60 ft., passive Perception 13
Languages Taldan, Goblin, Hallit, Orc
Challenge 4 (1,100 XP)
During Combat. Marrow relies on her zombies to engage the enemy in melee, all owing her to hang back and use her ranged spells on foes. She switches to her wands once her spells are exhausted, and does her best to stay mobile in a battle and out of melee entirely-her dagger is only for last resorts. She prefers to use her channeled negative energy for healing her precious undead minions..
Other Gear. dagger, cloak of resistance +1, 48 gp.
Spellcasting. Marrow is a 6th level spellcaster. Its spellcasting ability is Charisma (spell save DC 14, +6 to hit with spell attacks). Marrow can cast the following spells:
Cantrip (at will): Chill Touch, Ray of Frost, Minor Illusion
1 level (4 slots): Charm Person, Mage Armor, Ray of Sickness, Shield
2 level (3 slots): Blindness/Deafness, Mirror Image, Ray of Enfeeblement, Misty Step
3 level (3 slots): Animate Dead, Counterspell, Fear, Lightning Bolt
4 level (1 slot): Blight, Greater Invisibility
Actions
Dagger. Melee or Ranged Weapon Attack: +5 to hit, reach ft. or range 20/60 ft., one target. Hit: 5 (1d4 + 3) piercing damage.

**Comment by mlenser** [comment]
I get this regularly. Is this the HP issue?

Happened with !shaped-monster --manticore

Happened with statblock import:
Choker
Small aberration, chaotic evil
Armor Class 14 (natural armor)
Hit Points 18 (4d6 + 4)
Speed 20 ft., climb 10 ft.
STR
16 (+3)
DEX
14 (+2)
CON
13 (+1)
INT
4 (–3)
WIS
13 (+1)
CHA
7 (–2)
Skills Athletics +7, Stealth +6
Senses darkvision 60 ft., passive Perception 11
Languages Undercommon
Challenge 2 (450 XP)
Strangle. Chokers have an unerring talent for seizing their victims by the neck. A creature that is grappled by a choker cannot speak or cast spells with verbal components.
Quickness. A choker is supernaturally quick. It can take a bonus action on each of its turns to dash.
Actions
Multiattack. The choker makes two attacks with its tentacles.
Tentacles. Melee Weapon Attack: +5 to hit, reach 10 ft., one target. Hit: 5 (1d4 + 3) bludgeoning damage, and the target is grappled (escape DC 13).

**Comment by symposion** [comment]
Yes, check the imported character - most likely it will be fine - in which case this is just the HP rolling issue. Something about some recent changes to the sheet or the script has subtly altered the order/speed that things happen, and so some part of the HP formula isn't calculated by the time I try and roll it. I can't be bothered to faff about trying to fix it right now since this will all go away when I get the sheetworkers stuff rolled out - basically ready to go, but I'm waiting for 9.1.0 so that I can have all the minor tweaks in place to make it work smoothly.

**Comment by mlenser** [comment]
k
