### ISSUE TITLE
Shaped Script Monster Stat Block - Error Message in Console

### ISSUE THREAD

**Issue by symposion** [symposion/roll20-shaped-scripts#3]
_From @agjwilson on April 13, 2016 23:42_

I've tried using the script for the first time. 
My error is ERROR: You cannot set the imgsrc or avatar of an object unless you use an image that is in your Roll20 Library. See the API documentation for more info."

The image is in my library. Character Sheet for this monster is empty. (Repeated twice with different tokens and monsters)

I was using the command !shaped-import-statblock

_Copied from original issue: symposion/roll20-api-scripts#86_

**Comment by symposion** [comment]
_From @Brunhine on April 14, 2016 3:1_

This sometimes happens, even though everything works. Did the import fail to execute in this case? 

This is an error sent by Roll20, and not the script btw.

**Comment by symposion** [comment]
Is this issue solved now? I'm not sure who you are on Roll20 so I don't know if this is an issue that has been resolved already there?

**Comment by agjwilson** [comment]
yes resolved. I had not realised there was conflicts with new versions of character sheets which had been released since I last used a version of the shaped import script. Thank you.
