### ISSUE TITLE
9.1.1 shaped long/short rest issue

### ISSUE THREAD

**Issue by Salicar** [symposion/roll20-shaped-scripts#314]
Getting this error. but (!shaped-rest --long) works.  Not sure were it is going wrong.

(From ):
Shaped Scripts
Unrecognised or poorly formed option type long
Unrecognised or poorly formed option character -KdUncKIQsGszQj4H1ZB

**Comment by symposion** [comment]
Yeah, this is a mismatched script vs sheet issue. Wait for 9.2.0 sheet and 6.0.0 script to come out (should be real soon now) and this will be fixed.
