### ISSUE TITLE
 !shaped-update-character - undefined error

### ISSUE THREAD

**Issue by Jimwaters** [symposion/roll20-shaped-scripts#321]
Using shaped sheet 9.2.0 and companion 6.0.0
When trying to use !shaped-update-character I get errors

So tested with a new campaign - 
drag and drop Abjurer from VG1 - and converts to 9.2.0
Close sheet
Run !shaped-update-character --all 
error message
API Log:
"5eShapedCompanion 1487898476159 ERROR : TypeError: Cannot read property 'stream' of undefined\n at Importer.runImportStage (apiscript.js:6745:19)\n at apiscript.js:6989:15\n at process._tickCallback (node.js:406:9)"

Running the !shaped-update-character with Abjurer token selected - exactly the same error

Copied in a character from another campaign [7.12.1 version sheet] and try gain - same error message.

Converted new char to 9.2.0 by opening sheet 
Close sheet
running script get same error again

Note all errors were identical in every detail, including the numbers - except for the character ID

Full log of tests:-

"5eShapedCompanion 1487898476159 ERROR : TypeError: Cannot read property 'stream' of undefined\n    at Importer.runImportStage (apiscript.js:6745:19)\n    at apiscript.js:6989:15\n    at process._tickCallback (node.js:406:9)"
"Error: No attribute or sheet field found for character_id -Kdhdxb8kpY6EMWpalHA named sheet_opened"
"5eShapedCompanion 1487898756361 ERROR : TypeError: Cannot read property 'stream' of undefined"
"5eShapedCompanion 1487898756362 ERROR : TypeError: Cannot read property 'stream' of undefined\n    at Importer.runImportStage (apiscript.js:6745:19)\n    at apiscript.js:6989:15\n    at process._tickCallback (node.js:406:9)"
"Error: No attribute or sheet field found for character_id -KZ1Grr-KPbZ21U3fu0k named sheet_opened"
"5eShapedCompanion 1487898846696 ERROR : TypeError: Cannot read property 'stream' of undefined"
"5eShapedCompanion 1487898846696 ERROR : TypeError: Cannot read property 'stream' of undefined\n    at Importer.runImportStage (apiscript.js:6745:19)\n    at apiscript.js:6989:15\n    at process._tickCallback (node.js:406:9)"
"Error: No attribute or sheet field found for character_id -KZ1Grr-KPbZ21U3fu0k named sheet_opened"
"5eShapedCompanion 1487899806132 ERROR : TypeError: Cannot read property 'stream' of undefined"
"5eShapedCompanion 1487899806133 ERROR : TypeError: Cannot read property 'stream' of undefined\n    at Importer.runImportStage (apiscript.js:6745:19)\n    at apiscript.js:6989:15\n    at process._tickCallback (node.js:406:9)"
"Error: No attribute or sheet field found for character_id -Kdhdxb8kpY6EMWpalHA named sheet_opened"
"5eShapedCompanion 1487899831077 ERROR : TypeError: Cannot read property 'stream' of undefined"
"5eShapedCompanion 1487899831078 ERROR : TypeError: Cannot read property 'stream' of undefined\n    at Importer.runImportStage (apiscript.js:6745:19)\n    at apiscript.js:6989:15\n    at process._tickCallback (node.js:406:9)"

**Comment by Jimwaters** [comment]
Getting "Error: No attribute or sheet field found for character_id -KOz3L3leP4h7u--y0Gc named sheet_opened" for most characters converted - and for some getting 
"5eShapedCompanion 1489007813654 WARN : Found duplicate attributes from character Elister: [[\"version\",\"10.1.4\",\"\",\"-KOvdkcRCJ11nUvp8MrK\"],[\"version\",\"1.6\",\"\",\"-KOvdlMJFfQM4ToXsAi-
"5eShapedCompanion 1489007813701 WARN : Found duplicate attributes from character Elister: [[\"already_transitioned\",\"1\",\"\",\"-KOvdkcbO-1lB9qUxLgC\"],[\"already_transitioned\",\"1\",\"\",\"-KOvdlMNrekpHZf7nqVL\"]]"

 and then when run again getting the latter type of message for all that have already been processed.

Surely the errors should be warnings, and eventually the warnings tuned out?

**Comment by symposion** [comment]
The "Error" listed there is not an error at all. Roll20 prints this out when you request an attribute that doesn't exist - which is a reasonable way to check if the attribute exists! This shouldn't be printed, but it's not under my control and many people have pointed this out to Roll20 to no avail.

The warning is interesting - it looks like there's something funny going on with the OGL conversion process. Is this reliably happening for all characters that have been brought in from OGL?

**Comment by Jimwaters** [comment]
About 3% of SKT characters; and then most if rerun!
