### ISSUE TITLE
shaped companion script adding spurious ammo, not tracking use in chat

### ISSUE THREAD

**Issue by Gozer-the-Gozerian** [symposion/roll20-shaped-scripts#324]
Ammo tracking is set to "on", open a pre-existing character (upgraded from 9.0.1, now on 9.2.0), there are 3 ammo objects.  One decrements with use:
![screen shot 2017-02-24 at 9 12 45 am](https://cloud.githubusercontent.com/assets/25998862/23294184/e0903c16-fa72-11e6-87bd-ecb8ceb03ccf.png)
Chat still shows 19 arrows:
![screen shot 2017-02-24 at 9 12 53 am](https://cloud.githubusercontent.com/assets/25998862/23294199/ecec574c-fa72-11e6-9b63-fdbe9b7a2c93.png)
Adjust the number of arrows by editing the decrementing ammo object, and another one is added:
![screen shot 2017-02-24 at 9 13 32 am]
(https://cloud.githubusercontent.com/assets/25998862/23294235/0d61af04-fa73-11e6-8a8e-26a8142b0e2e.png)
API log:
![screen shot 2017-02-24 at 9 14 05 am](https://cloud.githubusercontent.com/assets/25998862/23294247/1a654526-fa73-11e6-832d-9552c154614d.png)

**Comment by symposion** [comment]
Hi, any chance you can paste more of the API log? You may need to scroll down, I need the whole lot from INFO : ~=> ShapedScripts v6.0.0 <=~ all the way to the last line - could be several hundred lines.

**Comment by Gozer-the-Gozerian** [comment]
That was the last line.  I already closed the window, but I'll see if I can replicate it.

Sorry, this is the best I've got now:

API sandbox shutdown due to campaign inactivity.
Spinning up new sandbox...
"Starting webworker script..."
"Loading 872 translation strings to worker..."
"5eShapedCompanion 1487922149393 INFO : -=> ShapedScripts v6.0.0 <=-"
"5eShapedCompanion 1487922149395 INFO : Checking config for upgrade, starting state: {\"version\":3.6,\"config\":{\"genderPronouns\":[{\"matchPattern\":\"^f$|female|girl|woman|feminine\",\"nominative\":\"she\",\"accusative\":\"her\",\"possessive\":\"her\",\"reflexive\":\"herself\"},{\"matchPattern\":\"^m$|male|boy|man|masculine\",\"nominative\":\"he\",\"accusative\":\"him\",\"possessive\":\"his\",\"reflexive\":\"himself\"},{\"matchPattern\":\"^n$|neuter|none|construct|thing|object\",\"nominative\":\"it\",\"accusative\":\"it\",\"possessive\":\"its\",\"reflexive\":\"itself\"}],\"logLevel\":\"INFO\",\"tokenSettings\":{\"number\":false,\"bar1\":{\"attribute\":\"HP\",\"max\":true,\"link\":false,\"showPlayers\":false},\"bar2\":{\"attribute\":\"AC\",\"max\":false,\"link\":true,\"showPlayers\":false},\"bar3\":{\"attribute\":\"\",\"max\":false,\"link\":false,\"showPlayers\":false},\"aura1\":{\"radius\":\"\",\"color\":\"#FFFF99\",\"square\":false},\"aura2\":{\"radius\":\"\",\"color\":\"#59e594\",\"square\":false},\"light\":{\"radius\":\"\",\"dimRadius\":\"\",\"otherPlayers\":false,\"hasSight\":true,\"angle\":360,\"losAngle\":360,\"multiplier\":1},\"showName\":true,\"showNameToPlayers\":false,\"showAura1ToPlayers\":true,\"showAura2ToPlayers\":true},\"newCharSettings\":{\"sheetOutput\":\"***default***\",\"deathSaveOutput\":\"***default***\",\"initiativeOutput\":\"***default***\",\"showNameOnRollTemplate\":\"{{show_character_name=1}}\",\"rollOptions\":\"***default***\",\"initiativeRoll\":\"\",\"initiativeToTracker\":0,\"breakInitiativeTies\":false,\"showTargetAC\":false,\"showTargetName\":false,\"autoAmmo\":true,\"autoRevertAdvantage\":true,\"houserules\":{\"mediumArmorMaxDex\":0,\"saves\":{\"useCustomSaves\":false,\"useAverageOfAbilities\":false,\"fortitude\":{\"fortitudeStrength\":false,\"fortitudeDexterity\":false,\"fortitudeConstitution\":false,\"fortitudeIntelligence\":false,\"fortitudeWisdom\":false,\"fortitudeCharisma\":false},\"reflex\":{\"reflexStrength\":false,\"reflexDexterity\":false,\"reflexConstitution\":false,\"reflexIntelligence\":false,\"reflexWisdom\":false,\"reflexCharisma\":false},\"will\":{\"willStrength\":false,\"willDexterity\":false,\"willConstitution\":false,\"willIntelligence\":false,\"willWisdom\":false,\"willCharisma\":false},\"savingThrowsHalfProf\":false},\"baseDC\":\"***default***\",\"expertiseAsAdvantage\":false,\"inspirationMultiple\":true,\"criticalDamageHouserule\":\"***default***\",\"proficiencyDice\":false,\"psionics\":false,\"customClasses\":false,\"honorToggle\":false,\"sanityToggle\":false},\"tab\":\"***default***\",\"tokenActions\":{\"initiative\":false,\"abilityChecks\":null,\"advantageTracker\":null,\"savingThrows\":null,\"attacks\":null,\"statblock\":false,\"traits\":null,\"actions\":null,\"reactions\":null,\"legendaryActions\":null,\"lairActions\":null,\"regionalEffects\":null,\"rests\":false,\"spells\":false,\"showRecharges\":false,\"racialFeatures\":null,\"classFeatures\":null,\"feats\":null},\"textSizes\":{\"spellsTextSize\":\"***default***\",\"abilityChecksTextSize\":\"***default***\",\"savingThrowsTextSize\":\"***default***\"},\"hide\":{\"hideAttack\":\"***default***\",\"hideDamage\":\"***default***\",\"hideAbilityChecks\":\"***default***\",\"hideSavingThrows\":\"***default***\",\"hideSavingThrowDC\":\"***default***\",\"hideSpellContent\":\"***default***\",\"hideSavingThrowFailure\":\"***default***\",\"hideSavingThrowSuccess\":\"***default***\",\"hideRecharge\":\"***default***\",\"hideFreetext\":\"***default***\",\"hideCost\":\"***default***\"},\"applyToAll\":true,\"hitDiceOutput\":\"***default***\",\"display\":{\"showPassiveSkills\":false,\"showWeight\":\"***default***\",\"showEmote\":false,\"showFreetext\":false,\"showFreeform\":false,\"showDiceModifiers\":false,\"showCritRange\":false,\"extraOnACrit\":false,\"showRests\":\"***default***\"},\"measurementSystems\":{\"distanceSystem\":\"***default***\",\"weightSystem\":\"***default***\",\"encumbranceMultiplier\":1},\"automaticHigherLevelQueries\":\"***default***\"},\"advTrackerSettings\":{\"showMarkers\":true,\"ignoreNpcs\":false,\"advantageMarker\":\"green\",\"disadvantageMarker\":\"red\",\"output\":\"silent\"},\"sheetEnhancements\":{\"rollHPOnDrop\":true,\"autoHD\":true,\"autoSpellSlots\":true,\"autoTraits\":true},\"defaultGenderIndex\":2,\"variants\":{\"rests\":{\"longNoHpFullHd\":false}}}}"
"sumRepeating"
"equipment.updateWeight"

Interestingly, although the chat is saying he has 19 arrows all the time, when I click on "Arrows" it shows the correct amount:
![screen shot 2017-02-24 at 9 44 03 am](https://cloud.githubusercontent.com/assets/25998862/23294810/f91a6704-fa75-11e6-9765-523ba3918f1b.png)

**Comment by symposion** [comment]
Hi, 

Could you take  a copy of the game, delete the two spurious ammo entries and try again? I can't recreate the issue with a new character sheet. My guess is that there's something that has gone wrong in an upgrade that has created the duplicate ammo entries, and once they're there, decrementing isn't working the way it ought to. If this is the case, deleting the spurious entries should fix the problem - and then you should log an issue on Kryx's issue tracker for the sheet for the fact that there are duplicate ammo entries being created during upgrade. If you can recreate this behaviour from the beginning reliably (do you have another character sheet/a copy that's still on 9.0.1?) that will definitely help Kryx out with tracking this down.

If deleting the entries doesn't help, or they come back, then I've misunderstood what's going on and it may be a problem with the script that happens in some special situations - I may need an invite to your game in that case.

**Comment by mlenser** [comment]
This is a sheet upgrade issue tracker by https://bitbucket.org/mlenser/5eshaped/issues/288/ammo-field-replicating

Remove the offending extra ammo fields and the rest of the bug should be handled there

**Comment by symposion** [comment]
This is a sheet issue as indicated by Kryx in the previous comment. Closing here.
