### ISSUE TITLE
Spell Tracking

### ISSUE THREAD

**Issue by beeke01** [symposion/roll20-shaped-scripts#329]
When configured to automatically track spells:
1.  Import Scorching Ray (or Heat Metal)
2.  Cast Scorching Ray and notice that a second level slot is decremented (good behavior!)
3.  From the chat box, use the Scorching Ray repeat link
4.  Notice that another second level spell slot is decremented (bad behavior!)

**Comment by Gozer-the-Gozerian** [comment]
Does the same with Magic Missile
