### ISSUE TITLE
Importing Spell List gives an error

### ISSUE THREAD

**Issue by NeighbourJim** [symposion/roll20-shaped-scripts#334]
Did !shaped-import-spell-list --classes Cleric, got an error instead (http://puu.sh/ujgTO/a24a5d0964.png)

The error I get in the console is as follows: 
``"5eShapedCompanion 1488032668891 ERROR : TypeError: Cannot read property '1' of null"
"5eShapedCompanion 1488032668892 ERROR : TypeError: Cannot read property '1' of null\n    at apiscript.js:8814:89\n    at /home/node/d20-api-server/node_modules/underscore/underscore.js:399:19\n    at Function._.each._.forEach (/home/node/d20-api-server/node_modules/underscore/underscore.js:153:9)\n    at Function.groupBy (/home/node/d20-api-server/node_modules/underscore/underscore.js:398:9)\n    at _.(anonymous function) [as groupBy] (/home/node/d20-api-server/node_modules/underscore/underscore.js:1496:34)\n    at Importer.getSpellAttributesForCharacter (apiscript.js:8814:9)\n    at Importer.getSpellAttributesForImport (apiscript.js:8839:26)\n    at apiscript.js:8802:44\n    at process._tickCallback (node.js:406:9)"``

Adding spells one-by-one with !shaped-import-spell works fine.

**Comment by symposion** [comment]
Looking at the code, I suspect that you may have run this on a character that hadn't yet been fully upgraded to 9.x by the sheet. I'll put a guard in to prevent the error and I might put something in that checks versions to avoid unpleasant surprises!
