### ISSUE TITLE
Spell importer

### ISSUE THREAD

**Issue by Salicar** [symposion/roll20-shaped-scripts#353]
sheet 9.2.3 compan 6.4.2
Not sure if i post is here or on the fourms.(posted on both) getting this error with spell importer for a single spell on a pc. !shaped-spell is what i was using.

"5eShapedCompanion 1488139232095 ERROR : TypeError: Cannot read property 'name' of undefined"
"5eShapedCompanion 1488139232096 ERROR : TypeError: Cannot read property 'name' of undefined\n    at apiscript.js:5704:51\n    at Function._.map._.collect (/home/node/d20-api-server/node_modules/underscore/underscore.js:172:24)\n    at apiscript.js:5704:17"

**Comment by symposion** [comment]
Should be fixed in 6.4.4 - have a go now.
