### ISSUE TITLE
Odd Stat Block  "Undefined Skills" %{selected|shaped_statblock}

### ISSUE THREAD

**Issue by agjwilson** [symposion/roll20-shaped-scripts#356]
%{selected|shaped_statblock}

Shaped Sheet 9.2.3 
Companion 6.4.0

![error-owc](https://cloud.githubusercontent.com/assets/18452351/23344556/8ee1a07a-fc76-11e6-8d8b-3f6cb792c9cb.jpg)

**Comment by symposion** [comment]
I can't reproduce this, but I'll leave this open for the moment in case other people start seeing this. If you see it again, please post.

**Comment by symposion** [comment]
I think that this is going to go away when the latest changes are rolled out from dev onto main.
