### ISSUE TITLE
Saves/Skills importing a monster

### ISSUE THREAD

**Issue by beeke01** [symposion/roll20-shaped-scripts#366]
Shaped 9.2.3, Companion 6.4.6

I honestly am unsure if this is a script issue, sheet issue, or possibly json data issue, so if it is a problem elsewhere, just let me know and I can either report it to Mark, or try to fix the json data.  I am using the latest json data from Mark's github.

When importing a monster (complex monster in this case), the saving throw and skill proficiencies are correctly "checked", however the calculated values of them are not updated properly until you uncheck and recheck them.

1) !shaped-import-monster --Strahd von Zarovich
2) Allow the import to complete
3) Upon opening the sheet and switching to edit mode you will notice saves and skills are marked properly for proficiency/expertise, however the calculated values are not correct, specifically the Proficiency Bonus is not applied to the calculated value.

![capture](https://cloud.githubusercontent.com/assets/8306402/23378082/1cb57dac-fd00-11e6-803d-b326a8cc8f01.JPG)

Log:
"5eShapedCompanion 1488225638565 INFO : Detected sheet version as : 9.2.3"
"ERROR: You cannot set the imgsrc or avatar of an object unless you use an image that is in your Roll20 Library. See the API documentation for more info."
"ERROR: You cannot set the imgsrc or avatar of an object unless you use an image that is in your Roll20 Library. See the API documentation for more info."
"Error: No attribute or sheet field found for character_id -Ke0BUkIYY2yMmz-aOdY named version"
"settings.updateShapedD20"
"abilityChecks.updateInitiative"
"abilityChecks.updateInitiative"
"savingThrows.updateMacro"
"savingThrows.update"
"spells.updateDCAndAttack"
"abilities.update"
"proficiencyBonus.update"
"savingThrows.update"
"spells.updateDCAndAttack"
"savingThrows.updateMacro"
"savingThrows.updateMacro"
"settings.updateWeightSystem"
"equipment.updateEncumbered"
"equipment.updateHeavilyEncumbered"
"spells.generateHigherLevelQueries"
"initialize.sheetOpened"
"sumRepeating"
"abilityChecks.updateMacro"
"abilityChecks.updateMacro"
"sumRepeating"
"sumRepeating"
"abilities.update"
"abilityChecks.updateMacro"
"equipment.setAdvantageOnStealth"
"equipment.updateWeight"
"equipment.setAdvantageOnStealth"
"equipment.updateWeight"
"equipment.updateWeight"
"abilities.update"
"spells.updateDCAndAttack"
"abilityChecks.updateInitiative"
"equipment.updateCarryingCapacity"
"equipment.updateMaxPushDragLift"
"equipment.updateEncumbered"
"equipment.updateHeavilyEncumbered"
"savingThrows.update"
"abilities.update"
"spells.updateDCAndAttack"
"abilityChecks.updateInitiative"
"savingThrows.update"
"abilities.update"
"spells.updateDCAndAttack"
"abilityChecks.updateInitiative"
"savingThrows.update"
"abilities.update"
"spells.updateDCAndAttack"
"abilityChecks.updateInitiative"
"savingThrows.update"
"abilities.update"
"spells.updateDCAndAttack"
"abilityChecks.updateInitiative"
"savingThrows.update"
"abilities.update"
"spells.updateDCAndAttack"
"abilityChecks.updateInitiative"
"savingThrows.update"
"abilityChecks.updateSkill"
"sumRepeating"
"abilityChecks.updateSkill"
"abilityChecks.updateSkill"
"sumRepeating"
"abilityChecks.updateSkill"
"sumRepeating"
"abilityChecks.updateSkill"
"sumRepeating"
"abilityChecks.updateSkill"
"abilityChecks.updateSkill"
"sumRepeating"
"abilityChecks.updateSkill"
"abilityChecks.updateSkill"
"sumRepeating"
"abilityChecks.updateSkill"
"abilityChecks.updateSkill"
"sumRepeating"
"abilityChecks.updateSkill"
"equipment.updateWeight"
"equipment.updateWeight"
"equipment.updateWeight"
"equipment.updateWeight"
"equipment.updateWeight"
"equipment.updateWeight"
"equipment.updateWeight"
"abilityChecks.updateMacro"
"abilityChecks.updateMacro"
"abilityChecks.updateMacro"
"abilityChecks.updateMacro"
"npc.updateSize"
"npc.updateAC"
"npc.updateHPFromSRD"
"speed.update"
"abilities.update"
"npc.updateChallenge"
"proficiencyBonus.update"
"spells.updateDCAndAttack"
"savingThrows.updateFromSRD"
"resistances.updateDamageResistancesVar"
"senses.update"
"npc.updateLanguages"
"npc.switchTo"
"npc.updateContent"
"abilityChecks.updateMacro"
"abilityChecks.updateMacro"
"abilityChecks.updateMacro"
"abilityChecks.updateMacro"
"abilityChecks.updateMacro"
"abilityChecks.updateMacro"
"abilityChecks.updateMacro"
"abilityChecks.updateMacro"
"abilityChecks.updateSkillsFromSRD"
"actions.update trait, action, reaction, legendaryaction, lairaction, regionaleffect undefined"
"actions.updateChatMacro"
"spells.findSpellcasting"
"spells.parseSpellcasting"
"actions.updateChatMacro"
"actions.updateChatMacro"
"actions.updateChatMacro"
"actions.update trait -Ke0BXhcgC9oAVNql97I"
"actions.updateChatMacro"
"actions.update action -Ke0BXhcgC9oAVNql97G"
"actions.updateChatMacro"
"spells.updateDCAndAttack"
"spells.updateSlots"
"spells.updateHasSpellSlots"
"spells.updateChatMacro"
"spells.generateHigherLevelQueries"
"spells.updateShowHide"
"spells.updateShowHide"

**Comment by beeke01** [comment]
I retested this with Shaped 10.0.1 and Companion Script 7.0.0 and the problem remains the same.

**Comment by symposion** [comment]
Urgh. This doesn't happen for me, which means that it's a non-deterministic bug. Sigh. Could you do !logLevel 5eShapedCompanion DEBUG, try again, and then attach the log as a text file to this ticket? I need to see whether the problem is with the Roll20 API sheetworkers implementation lying about when sheetworkers complete, or whether there's an inherent non-determinism in the sheetworkers themselves. I suspect the latter, but I'm not sure how easy it will be for Kryx to fix it...

**Comment by symposion** [comment]
Hmm. Actually, don't bother. I think I can fix this from my end if I force CR to be imported in an early phase before skills/saves.

**Comment by symposion** [comment]
Hey, I think I might have misdiagnosed this. Do you Proficiency Dice turned on?

**Comment by symposion** [comment]
> Hey, I think I might have misdiagnosed this. Do you Proficiency Dice turned on?

No, that's clearly not it. There's something very odd going on here. Looking at Kryx's code this really shouldn't be possible unless something is epically broken with Roll20. Try the next release and see if it makes a difference.
