### ISSUE TITLE
Uses Police Request

### ISSUE THREAD

**Issue by beeke01** [symposion/roll20-shaped-scripts#367]
Currently the Uses Police chat message is sent to everyone.  It would be beneficial to have a configuration for this message to allow you to have it whisper the GM (at least for NPCs or sheets that are set to /w GM).

**Comment by symposion** [comment]
Yeah, ok. I will make uses and rests whisper to the player who clicked on the trait/action/whatever  if the sheet_output option is set to whisper, otherwise it will be public
