### ISSUE TITLE
!shaped-abilities --attacks not recognizing attacks

### ISSUE THREAD

**Issue by Gozer-the-Gozerian** [symposion/roll20-shaped-scripts#368]
Script 7.0.0, Sheet 10.0.1

Trying to create token actions using the !shaped-abilities --attacks, but the script says the character has no attacks.  Then run !shaped-abilities --actions, and it creates actions successfully.

API log:

"5eShapedCompanion 1488264156769 INFO : Configuration state: {\"version\":4.1,\"config\":{\"genderPronouns\":[{\"matchPattern\":\"^f$|female|girl|woman|feminine\",\"nominative\":\"she\",\"accusative\":\"her\",\"possessive\":\"her\",\"reflexive\":\"herself\"},{\"matchPattern\":\"^m$|male|boy|man|masculine\",\"nominative\":\"he\",\"accusative\":\"him\",\"possessive\":\"his\",\"reflexive\":\"himself\"},{\"matchPattern\":\"^n$|neuter|none|construct|thing|object\",\"nominative\":\"it\",\"accusative\":\"it\",\"possessive\":\"its\",\"reflexive\":\"itself\"}],\"logLevel\":\"INFO\",\"tokenSettings\":{\"number\":false,\"bar1\":{\"attribute\":\"HP\",\"max\":true,\"link\":false,\"showPlayers\":false},\"bar2\":{\"attribute\":\"AC\",\"max\":false,\"link\":true,\"showPlayers\":false},\"bar3\":{\"attribute\":\"\",\"max\":false,\"link\":false,\"showPlayers\":false},\"aura1\":{\"radius\":\"\",\"color\":\"#FFFF99\",\"square\":false},\"aura2\":{\"radius\":\"\",\"color\":\"#59e594\",\"square\":false},\"light\":{\"radius\":\"\",\"dimRadius\":\"\",\"otherPlayers\":false,\"hasSight\":true,\"angle\":360,\"losAngle\":360,\"multiplier\":1},\"showName\":true,\"showNameToPlayers\":false,\"showAura1ToPlayers\":false,\"showAura2ToPlayers\":false,\"monsterTokenName\":\"\"},\"newCharSettings\":{\"sheetOutput\":\"***default***\",\"deathSaveOutput\":\"***default***\",\"initiativeOutput\":\"***default***\",\"showNameOnRollTemplate\":\"{{show_character_name=1}}\",\"rollOptions\":\"***default***\",\"initiativeRoll\":\"\",\"initiativeToTracker\":0,\"breakInitiativeTies\":false,\"showTargetAC\":false,\"showTargetName\":false,\"autoAmmo\":true,\"autoRevertAdvantage\":true,\"houserules\":{\"mediumArmorMaxDex\":0,\"saves\":{\"useCustomSaves\":false,\"useAverageOfAbilities\":false,\"fortitude\":{\"fortitudeStrength\":false,\"fortitudeDexterity\":false,\"fortitudeConstitution\":false,\"fortitudeIntelligence\":false,\"fortitudeWisdom\":false,\"fortitudeCharisma\":false},\"reflex\":{\"reflexStrength\":false,\"reflexDexterity\":false,\"reflexConstitution\":false,\"reflexIntelligence\":false,\"reflexWisdom\":false,\"reflexCharisma\":false},\"will\":{\"willStrength\":false,\"willDexterity\":false,\"willConstitution\":false,\"willIntelligence\":false,\"willWisdom\":false,\"willCharisma\":false},\"savingThrowsHalfProf\":false},\"baseDC\":\"***default***\",\"expertiseAsAdvantage\":false,\"inspirationMultiple\":true,\"criticalDamageHouserule\":\"***default***\",\"proficiencyDice\":false,\"psionics\":false,\"customClasses\":false,\"honorToggle\":false,\"sanityToggle\":false},\"tab\":\"***default***\",\"tokenActions\":{\"initiative\":false,\"abilityChecks\":null,\"advantageTracker\":null,\"savingThrows\":null,\"attacks\":null,\"statblock\":false,\"traits\":null,\"actions\":null,\"reactions\":null,\"legendaryActions\":null,\"lairActions\":null,\"regionalEffects\":null,\"rests\":false,\"spells\":false,\"showRecharges\":false,\"classFeatures\":null,\"feats\":null,\"racialTraits\":null},\"textSizes\":{\"spellsTextSize\":\"text\",\"abilityChecksTextSize\":\"text\",\"savingThrowsTextSize\":\"text\"},\"hide\":{\"hideAttack\":\"***default***\",\"hideDamage\":\"***default***\",\"hideAbilityChecks\":\"***default***\",\"hideSavingThrows\":\"***default***\",\"hideSavingThrowDC\":\"***default***\",\"hideSavingThrowFailure\":\"***default***\",\"hideSavingThrowSuccess\":\"***default***\",\"hideRecharge\":\"***default***\",\"hideFreetext\":\"***default***\",\"hideCost\":\"***default***\",\"hideContent\":\"***default***\"},\"applyToAll\":false,\"hitDiceOutput\":\"***default***\",\"display\":{\"showPassiveSkills\":false,\"showWeight\":\"***default***\",\"showEmote\":false,\"showFreetext\":false,\"showFreeform\":false,\"showDiceModifiers\":false,\"showCritRange\":false,\"extraOnACrit\":false,\"showRests\":\"***default***\"},\"measurementSystems\":{\"distanceSystem\":\"***default***\",\"weightSystem\":\"***default***\",\"encumbranceMultiplier\":1},\"automaticHigherLevelQueries\":\"***default***\",\"automaticallyExpendSpellResources\":true},\"advTrackerSettings\":{\"showMarkers\":false,\"ignoreNpcs\":false,\"advantageMarker\":\"green\",\"disadvantageMarker\":\"red\",\"output\":\"silent\"},\"sheetEnhancements\":{\"rollHPOnDrop\":true,\"autoHD\":true,\"autoTraits\":true},\"defaultGenderIndex\":2,\"variants\":{\"rests\":{\"longRestHDRecovery\":0.5,\"longRestHPRecovery\":0}},\"playerId\":\"-KcabPQPBh5r48GEjykc\"}}"
Restarting sandbox due to script changes...
Previous shutdown complete, starting up...
Spinning up new sandbox...
"Starting webworker script..."
"Loading 874 translation strings to worker..."
"5eShapedCompanion 1488264397623 INFO : -=> ShapedScripts v7.0.0 <=-"
"ERROR: You cannot set the imgsrc or avatar of an object unless you use an image that is in your Roll20 Library. See the API documentation for more info."
"5eShapedCompanion 1488264397704 INFO : Summary of adding CurseOfStrahd entity group to the lookup: {\"errors\":0,\"entityGroupName\":{},\"monsters\":{\"withErrors\":0,\"skipped\":0,\"deleted\":0,\"patched\":0,\"added\":20}}"
"5eShapedCompanion 1488264397717 INFO : Summary of adding HoardOfTheDragonQueen entity group to the lookup: {\"errors\":0,\"entityGroupName\":{},\"monsters\":{\"withErrors\":0,\"skipped\":0,\"deleted\":0,\"patched\":0,\"added\":15}}"
"5eShapedCompanion 1488264397720 INFO : Summary of adding LostMineOfPhandelver entity group to the lookup: {\"errors\":0,\"entityGroupName\":{},\"monsters\":{\"withErrors\":0,\"skipped\":0,\"deleted\":0,\"patched\":0,\"added\":5}}"
"5eShapedCompanion 1488264397949 INFO : Summary of adding MonsterManual entity group to the lookup: {\"errors\":0,\"entityGroupName\":{},\"monsters\":{\"withErrors\":0,\"skipped\":0,\"deleted\":0,\"patched\":0,\"added\":454}}"
"5eShapedCompanion 1488264397968 INFO : Summary of adding OutOfTheAbyss entity group to the lookup: {\"errors\":0,\"entityGroupName\":{},\"monsters\":{\"withErrors\":0,\"skipped\":0,\"deleted\":0,\"patched\":0,\"added\":35}}"
"5eShapedCompanion 1488264397990 INFO : Summary of adding PrincesOfTheApocalypse entity group to the lookup: {\"errors\":0,\"entityGroupName\":{},\"monsters\":{\"withErrors\":0,\"skipped\":0,\"deleted\":0,\"patched\":0,\"added\":42}}"
"5eShapedCompanion 1488264397994 INFO : Summary of adding TheRiseOfTiamat entity group to the lookup: {\"errors\":0,\"entityGroupName\":{},\"monsters\":{\"withErrors\":0,\"skipped\":0,\"deleted\":0,\"patched\":0,\"added\":7}}"
"5eShapedCompanion 1488264398210 INFO : Summary of adding TomeOfBeasts entity group to the lookup: {\"errors\":0,\"entityGroupName\":{},\"monsters\":{\"withErrors\":0,\"skipped\":0,\"deleted\":0,\"patched\":0,\"added\":406}}"
"5eShapedCompanion 1488264398225 INFO : Summary of adding spellData entity group to the lookup: {\"errors\":0,\"entityGroupName\":{},\"spells\":{\"withErrors\":0,\"skipped\":0,\"deleted\":0,\"patched\":0,\"added\":408}}"
"initialize.sheetOpened"
"abilities.update"
"abilityChecks.updateInitiative"
"savingThrows.updateMacro"
"initialize.generateSkills"
"abilityChecks.updateMacro"
"abilityChecks.updateSkill"
"abilityChecks.updateMacro"
"5eShapedCompanion 1488264400233 INFO : Detected sheet version as : 10.0.1"
"5eShapedCompanion 1488264400237 INFO : Configuration state: {\"version\":4.1,\"config\":{\"genderPronouns\":[{\"matchPattern\":\"^f$|female|girl|woman|feminine\",\"nominative\":\"she\",\"accusative\":\"her\",\"possessive\":\"her\",\"reflexive\":\"herself\"},{\"matchPattern\":\"^m$|male|boy|man|masculine\",\"nominative\":\"he\",\"accusative\":\"him\",\"possessive\":\"his\",\"reflexive\":\"himself\"},{\"matchPattern\":\"^n$|neuter|none|construct|thing|object\",\"nominative\":\"it\",\"accusative\":\"it\",\"possessive\":\"its\",\"reflexive\":\"itself\"}],\"logLevel\":\"INFO\",\"tokenSettings\":{\"number\":false,\"bar1\":{\"attribute\":\"HP\",\"max\":true,\"link\":false,\"showPlayers\":false},\"bar2\":{\"attribute\":\"AC\",\"max\":false,\"link\":true,\"showPlayers\":false},\"bar3\":{\"attribute\":\"\",\"max\":false,\"link\":false,\"showPlayers\":false},\"aura1\":{\"radius\":\"\",\"color\":\"#FFFF99\",\"square\":false},\"aura2\":{\"radius\":\"\",\"color\":\"#59e594\",\"square\":false},\"light\":{\"radius\":\"\",\"dimRadius\":\"\",\"otherPlayers\":false,\"hasSight\":true,\"angle\":360,\"losAngle\":360,\"multiplier\":1},\"showName\":true,\"showNameToPlayers\":false,\"showAura1ToPlayers\":false,\"showAura2ToPlayers\":false,\"monsterTokenName\":\"\"},\"newCharSettings\":{\"sheetOutput\":\"***default***\",\"deathSaveOutput\":\"***default***\",\"initiativeOutput\":\"***default***\",\"showNameOnRollTemplate\":\"{{show_character_name=1}}\",\"rollOptions\":\"***default***\",\"initiativeRoll\":\"\",\"initiativeToTracker\":0,\"breakInitiativeTies\":false,\"showTargetAC\":false,\"showTargetName\":false,\"autoAmmo\":true,\"autoRevertAdvantage\":true,\"houserules\":{\"mediumArmorMaxDex\":0,\"saves\":{\"useCustomSaves\":false,\"useAverageOfAbilities\":false,\"fortitude\":{\"fortitudeStrength\":false,\"fortitudeDexterity\":false,\"fortitudeConstitution\":false,\"fortitudeIntelligence\":false,\"fortitudeWisdom\":false,\"fortitudeCharisma\":false},\"reflex\":{\"reflexStrength\":false,\"reflexDexterity\":false,\"reflexConstitution\":false,\"reflexIntelligence\":false,\"reflexWisdom\":false,\"reflexCharisma\":false},\"will\":{\"willStrength\":false,\"willDexterity\":false,\"willConstitution\":false,\"willIntelligence\":false,\"willWisdom\":false,\"willCharisma\":false},\"savingThrowsHalfProf\":false},\"baseDC\":\"***default***\",\"expertiseAsAdvantage\":false,\"inspirationMultiple\":true,\"criticalDamageHouserule\":\"***default***\",\"proficiencyDice\":false,\"psionics\":false,\"customClasses\":false,\"honorToggle\":false,\"sanityToggle\":false},\"tab\":\"***default***\",\"tokenActions\":{\"initiative\":false,\"abilityChecks\":null,\"advantageTracker\":null,\"savingThrows\":null,\"attacks\":null,\"statblock\":false,\"traits\":null,\"actions\":null,\"reactions\":null,\"legendaryActions\":null,\"lairActions\":null,\"regionalEffects\":null,\"rests\":false,\"spells\":false,\"showRecharges\":false,\"classFeatures\":null,\"feats\":null,\"racialTraits\":null},\"textSizes\":{\"spellsTextSize\":\"text\",\"abilityChecksTextSize\":\"text\",\"savingThrowsTextSize\":\"text\"},\"hide\":{\"hideAttack\":\"***default***\",\"hideDamage\":\"***default***\",\"hideAbilityChecks\":\"***default***\",\"hideSavingThrows\":\"***default***\",\"hideSavingThrowDC\":\"***default***\",\"hideSavingThrowFailure\":\"***default***\",\"hideSavingThrowSuccess\":\"***default***\",\"hideRecharge\":\"***default***\",\"hideFreetext\":\"***default***\",\"hideCost\":\"***default***\",\"hideContent\":\"***default***\"},\"applyToAll\":false,\"hitDiceOutput\":\"***default***\",\"display\":{\"showPassiveSkills\":false,\"showWeight\":\"***default***\",\"showEmote\":false,\"showFreetext\":false,\"showFreeform\":false,\"showDiceModifiers\":false,\"showCritRange\":false,\"extraOnACrit\":false,\"showRests\":\"***default***\"},\"measurementSystems\":{\"distanceSystem\":\"***default***\",\"weightSystem\":\"***default***\",\"encumbranceMultiplier\":1},\"automaticHigherLevelQueries\":\"***default***\",\"automaticallyExpendSpellResources\":true},\"advTrackerSettings\":{\"showMarkers\":false,\"ignoreNpcs\":false,\"advantageMarker\":\"green\",\"disadvantageMarker\":\"red\",\"output\":\"silent\"},\"sheetEnhancements\":{\"rollHPOnDrop\":true,\"autoHD\":true,\"autoTraits\":true},\"defaultGenderIndex\":2,\"variants\":{\"rests\":{\"longRestHDRecovery\":0.5,\"longRestHPRecovery\":0}},\"playerId\":\"-KcabPQPBh5r48GEjykc\"}}"
"5eShapedCompanion 1488264427745 ERROR : Error: Error: Character Skeleton is not at the required sheet version [10.0.1], but instead [9.0.1]. Try opening the character sheet or running !shaped-update-character to update it."

**Comment by symposion** [comment]
Hi Gozer,

A couple of things here.

1. In your log there it's saying that you've tried to do something with a Skeleton character but it failed because the character wasn't updated to the latest version. Did you resolve this by opening the sheet or running !shaped-update-character?
2. What character(s) were you running this on? Do they have attacks? Bear in mind that NPCs don't have attacks - they only have actions. Attacks is a PC-only thing.

**Comment by Gozer-the-Gozerian** [comment]
1. Yes I updated the skeleton character, and I was able to use the --actions command on it.

2. Both characters were NPCs, so...sorry about that.  I guess it's working as intended.  *sheepish grin*
