### ISSUE TITLE
!shaped-monsters and !shaped-spells adjustments

### ISSUE THREAD

**Issue by mlenser** [symposion/roll20-shaped-scripts#396]
Can you make the following adjustments for monsters and spells:

1. For the filters add a heading. Something like `<span class="heading">Type.</span> aberration`
2. Add a comma between each filter item to make it more readable. So "aberration, beast, celestial". Comma should not be part of the link so the black color should also help with separation.
3. Give each filter wrapper div a class so I can add some small amount of padding in between each one if needed.
4. Capitalize "Monsters" and "Spells"
5. Rename "Click to select a monster" to "Select a monster via query" or something similar. "select a spell via query" would work for spells
6. Move "Select a monster.." to the top under the title
7. Add a class name on the div that scrolls so I can style it.
8. Remove line breaks between each link in the scroll div.
9. Wrap each button in the scroll div in a `<span>`
10. Remove the current inline styling. Perhaps send me a copy of what you have now if it's important. Otherwise I can probably figure it out.
11. Add a class to a selected filter so I can style it.
12. Can spell archetypes go into a different div?
13. Archetypes currently aren't limited by class, is that intended? We had discussed limiting them by class.
14. Add more spell filters for things like ritual and concentration. Ritual would search for spells that are a ritual. "No concentration" as I've now named it on the sheet would search for spells without concentration. I'd also suggesting adding one based on casting time as that can be useful.
15. ~~"Conjuration" and "conjuration" both appear in the school list, but that is a data issue which I've fixed.~~

Looking good overall though.

**Comment by symposion** [comment]
Ok, so I think all of these are straightforward and I can do them; the only thing we need to discuss is (13). The problem with restricting archetypes by class is that in some cases you will want to view just the archetype spells on their own, without the main class spell list. We talked about this but parked it and didn't come up with a solution.

I've thought about it a bit more and I think that the UI that would make the most sense is this:
- Select one or more classes from a list of just classes
- For each selected class, if it has archetypes with spell lists, show a new line that includes the archetypes plus "Main". "Main" will be selected by default, and will include all the core spells for that class. You can uncheck it if you just want to see the spells for an archetype, or leave it checked and add spells from one or more archetypes.

What do you think?

**Comment by mlenser** [comment]
I think that's a great idea. Though "Main" can probably be worded more clearly. "Class" or the name of the class ("Druid") are both probably more clear. I'd go with "Class" probably.

**Comment by symposion** [comment]
I think I've done the styling items now, I need to do 13 and 14 but that will be tomorrow now.

**Comment by symposion** [comment]
Also, I need to fix source names to be friendlier by putting spaces and fixing casing

**Comment by mlenser** [comment]
Source names are moving to the config so I'm going to show the full names again.

**Comment by mlenser** [comment]
Another step: Add a patch system. Possibly use my houserules as an example or a more simple case and I can update mine.

**Comment by symposion** [comment]
As regards the patch system, what's wrong with the patch system we have now?

**Comment by mlenser** [comment]
You said it'd take you a few days to make it work. Does it work already?

**Comment by symposion** [comment]
Yeah :-)
