### ISSUE TITLE
!shaped-config changes

### ISSUE THREAD

**Issue by mlenser** [symposion/roll20-shaped-scripts#409]
1. "Main Menu" and similar titles should appear as a subheader: `{{subheader=Main Menu}}`.
2. Table structure should be replaced with divs unless there is some configuration that is showing tabular data. I can then set them up using flexbox.
3. Remove background from links (red, teal and blueish colors)
4. Toggleable options that are off should have `.userscript-notselected` added. So all options that are on will be pink and all options that are off will be gray as is standard elsewhere. Normal links will be pink.
5. Advantage/Disadvantage colors should be alphabetized. (besides the currently selected option which should be at the top)
6. Encumbrance Multiplier should be removed from "Measurement Systems".
7. Text sizes should be removed if they're for ability checks, saving throws, and spells as I removed them from the sheet.
8. Houserule settings should match the new order and add hit points and hit dice recovery. Multiple inspiration is moved to the end, medium armor is above base DC.
9. new characters -> Death saves options should match the options presented on the sheet. The wording and number of options currently doesn't match. Same for Hit Dice
10. new character -> hide settings -> remove "Hide saving throw success" and add "Hide target AC" after "Hide Recharge". You can see this setting if you have "Target's AC on Attacks" toggled on.
11. new character -> display -> Remove "Show rests".
12. Options like "Automatically revert.. " should be presented in the same grouping as the sheet. Same for roll template, output, initiative, etc.
13. Roll template options should add auto rolling damage options.

**Comment by symposion** [comment]
Have made https://github.com/symposion/roll20-shaped-scripts/issues/410 for the html structure, but otherwise I think this is done.
