### ISSUE TITLE
TypeError in log on 8.2.0 with sheet 11.0.3

### ISSUE THREAD

**Issue by liquidox** [symposion/roll20-shaped-scripts#417]
I have already run the config updater as well as the character updater on this campaign.

---

"TypeError: Cannot read property 'replace' of undefined"

"TypeError: Cannot read property 'replace' of undefined\n    at eval (eval at messageHandler (evalmachine.<anonymous>:282:6), <anonymous>:8:2619)\n    at Array.forEach (native)\n    at Object.process (eval at messageHandler (evalmachine.<anonymous>:282:6), <anonymous>:8:2056)\n    at Object.eval [as -KfxtCMhnofbkY--eYIM//false//0.28305818277668915] (eval at messageHandler (evalmachine.<anonymous>:282:6), <anonymous>:89:2823)\n    at _fullfillAttrReq (evalmachine.<anonymous>:257:31)\n    at messageHandler (evalmachine.<anonymous>:288:6)\n    at process.<anonymous> (/home/node/d20-api-server/node_modules/tiny-worker/lib/worker.js:68:55)\n    at emitTwo (events.js:106:13)\n    at process.emit (events.js:194:7)\n    at process.nextTick (internal/child_process.js:766:12)"

"5eShapedCompanion 1490318320168 INFO : Detected sheet version as : 11.0.3"

**Comment by joesinghaus** [comment]
Getting the same thing. This happens on startup.

**Comment by symposion** [comment]
Hmm. I think this may still be a Roll20 problem. I thought we'd nailed this stuff, sigh. It doesn't crash the sandbox because I'm catching the error and reporting it rather than letting it propagate up. 
At the moment I think it's probably harmless but I'd like to work out what's going on.

**Comment by mlenser** [comment]
Let me know if this ends up being a sheet error. I don't think it is, but maybe.

**Comment by symposion** [comment]
This is a sheet bug: https://bitbucket.org/mlenser/5eshaped/issues/401/abilitychecksupdatemacro-should-be-in

Closing here, please watch that issue for updates.
