### ISSUE TITLE
Docs update!

### ISSUE THREAD

**Issue by symposion** [symposion/roll20-shaped-scripts#421]
New entity list commands + !shaped-abilities stuff + config options

**Comment by liquidox** [comment]
I am working on this, will take a bit longer as I just got your PR-tips in the mail, so posting here to make sure you're not doing double work.

**Comment by symposion** [comment]
Oh wow - that would be awesome! I've been procrastinating about updating the docs because... well... docs :-) I really appreciate the help - hopefully all of the various git/build hurdles I've thrown in your way won't put you off contributing!
