### ISSUE TITLE
No attribute or sheet field found for character_id

### ISSUE THREAD

**Issue by liquidox** [symposion/roll20-shaped-scripts#426]
While testing #425 I noted this in the error log:

"Error: No attribute or sheet field found for character_id -Kg4gRcFjPBTqKqF3m23 named repeating_legendaryaction_-Kg4gS-D2XY1N3Jpe4tb_recharge"

Or is this a Sheet bug?

**Comment by symposion** [comment]
It's actually not a bug at all. Well, actually it is, but it's a bug in Roll20, insofar as it spits out this error for something that is clearly not an error at all. See https://app.roll20.net/forum/permalink/4818851/

**Comment by liquidox** [comment]
Ah so a variant of that same "error" then, good to know.
