### ISSUE TITLE
Re-introduce startup delay

### ISSUE THREAD

**Issue by symposion** [symposion/roll20-shaped-scripts#441]
Make it delay if it doesn't find a version attribute - trying again repeatedly for up to 20 seconds before giving up.

**Comment by liquidox** [comment]
I've seen this once today, I don't mind loading a debug version and seeing if I can reproduce it sometimes.

Mine was:
"5eShapedCompanion 1490787091753 INFO : Detected sheet version as : undefined"

PS.
I am also getting:

"Error: No attribute or sheet field found for character_id -KgOpR9ki-sb0bcVF9L0 named version"
"Error: No attribute or sheet field found for character_id -KcsyziMOLFvlp1gJaxt named sheet_opened"
"data.skills_srd"

New, or related to a previous bug? I remember similar errors...

**Comment by symposion** [comment]
Hey, yeah, I've been debugging this in someone else SKT campaign. It's the same bug as before but I thought Riley had nailed at the Roll20 end. Basically the sheetworker completion callback is getting called before the sheetworkers are actually complete. In fact, in this case, it gets called before they even start. What other script do you have installed in the campaign, BTW?

**Comment by liquidox** [comment]
```
G  Critical
G  GroupInitiative
G  TokenNameNumber
TurnMarker
G  Vector Math
G  MatrixMath
G  Path Math
G  Torch
TokenMod
ApplyDamage
No Token Rotation
HealthColors
RollStats
Calendar
5eShapedCompanion
TableExport
G  Dynamic Light Helper
RecursiveTable
GroupCheck
ChatSetAttr
```

**Comment by symposion** [comment]
Yeah, so I suspect that HealthColors may be making this worse. It also does sheetworker stuff on startup (i believe) and I think there's a problem with the Roll20 implementation if multiple scripts are trying to fire off sheetworkers at the same time.
