### ISSUE TITLE
Hitpoint HD roller not working

### ISSUE THREAD

**Issue by liquidox** [symposion/roll20-shaped-scripts#444]
I just followed these steps:

1. Re-added YP to campaign.
2. Manually updated Skeleton character sheet, set defaults on token, redrag tokens, all OK.
3. Run the update cmd with --all flag. Saw this irregularity:
```
Updating character 36 - Kobold
(From ):
undefined
```
4. Set defaults on Goblin token, redrag token, HD not being rolled (default average HP is being set).
5. Same now happens to all tokens, and also to the original Skeleton tokens.
6. Restart sandbox
7. Skeletons now roll HD properly, other tokens still refuse to roll HD.

**Comment by liquidox** [comment]
Even running
!shaped-import-by-token --replace

On a non-HD-rolling token (e.g. Goblin) does not fix this.

**Comment by symposion** [comment]
Can you have a look at the tokens that don't work. Do they HP as a linked bar?

**Comment by liquidox** [comment]
Well...that was an easy fix. Didn't suspect that problem as it was working fine with the Skeleton!

Changed HP linking to "pcOnly" and now the Goblins are working fine.

**Comment by symposion** [comment]
Cool ok, I'm going to close then, unless you think there's still a problem here.
