### ISSUE TITLE
!shaped-import-statblock - Innate spellcasting messes with spell slots available

### ISSUE THREAD

**Issue by Jimwaters** [symposion/roll20-shaped-scripts#452]
Importing the stat block with both Innate Spellcasting and 5th Level spellcaster - causes spell slots to be set incorrectly as pic:-

![blag](https://cloud.githubusercontent.com/assets/25993570/24631799/9b6d105e-18b9-11e7-9912-7fe62946dca1.png)

Removing the Innate Spellcasting and running again, gives spell slots correctly.

Incidentally both versions make him a 1st-Level spell-caster for some reason!  

Blagothkus
Huge giant (cloud giant), neutral evil
Armor Class 17 (splint)
Hit Points 138 (12d12+60)
Speed 40ft.
STR DEX CON INT WIS CHA
26(+8) 13(+1) 20(+5) 16(+3) 15(+2) 15(+2)
Saving Throws Con +9, Wis +6, Cha +6
Skills Arcana +7, Insight +6, Intimidation +6, Perception +6
Senses passive Perception 16
Languages Common, Draconic, Giant
Challenge 9 (5,000XP)
Keen Smell. Blagothkus has advantage on Wisdom(Perception) checks that rely on smell.
Innate Spellcasting. Blagothkus can innately cast the following spells (spell save DC15), requiring no material components: 3/day each: fog cloud, levitate
Spellcasting. Blagothkus is a 5th-level spell caster that uses Intelligence as his spell casting ability (spell save DC15, +7 to hit with spell attacks). Blagothkus has the following spells prepared from the wizard spell list:
Cantrips (at will): light, mage hand, prestidigitation
1st level (4 slots): detect magic, identify, magic missile, shield
2nd level (3 slots): gust of wind, misty step, shatter
3rd level (2 slots): fly, lightning bolt
Actions______________________________________________
Multiattack. Blagothkus attacks twice with his morningstar.
Morningstar. Melee Weapon Attack: +10 to hit, reach 10ft., one target. Hit: 21 (3d8+8) piercing damage.

**Comment by Jimwaters** [comment]
The 5th level to 1st level change must be something to do with this statblock as I have tested with a known-working one [from previous versions] and that still works.

**Comment by Jimwaters** [comment]
Ok so it should say spellcaster not spell caster.  This resolves the 5th->1st change - but not the actual issue logged.

**Comment by symposion** [comment]
This is a sheet issue. I've opened https://bitbucket.org/mlenser/5eshaped/issues/435/race-condition-for-characters-with-both for Kryx to take a look, because I can't work out what's going on :-/
