### ISSUE TITLE
Initiative crashing API

### ISSUE THREAD

**Issue by gwhitneyy2k** [symposion/roll20-shaped-scripts#453]
Lucian getting a strange error. I have turned all the scripts off excepts for shaped sheet companion. I also reinstalled both the script and the sheet to make sure I don't have an error there. 
​
​Shaped Script Companion 8.4.2    Shaped Sheet 11.3.3
​
​The error seems to come when I sort the turn order or try to advance the turn. 
​
​Your scripts are currently disabled due to an error that was detected. Please make appropriate changes to your scripts and click the "Save Script" button and we'll attempt to start running them again. More info...
For reference, the error message generated was: TypeError: Cannot read property 'get' of null TypeError: Cannot read property 'get' of null at SheetWorkerChatOutput.displaySheetChatOutput (apiscript.js:8750:27) at roll20.setAttrWithWorker (apiscript.js:5244:35) at /home/node/d20-api-server/api.js:2140:5 at Function._.each._.forEach (/home/node/d20-api-server/node_modules/underscore/underscore.js:153:9) at handleSheetWorkerComplete (/home/node/d20-api-server/api.js:2139:5) at Timeout._onTimeout (/home/node/d20-api-server/api.js:2162:7) at ontimeout (timers.js:380:14) at tryOnTimeout (timers.js:244:5) at Timer.listOnTimeout (timers.js:214:5)

**Comment by symposion** [comment]
Yeah, sorry, oversight on my part. For the time being you can work around this by clicking one of the rests buttons *on the sheet* (NOT a token action) for the character in question. This will create the attribute that is missing and then you should be able to use the token actions again without things breaking.

I will put in a fix for this in the next version.

**Comment by gwhitneyy2k** [comment]
Thanks

**Comment by symposion** [comment]
This isn't actually fixed yet - not until the proper fix is released
