### ISSUE TITLE
Character is not at the required sheet version

### ISSUE THREAD

**Issue by mlenser** [symposion/roll20-shaped-scripts#488]
Error: Character Dehvira is not at the required sheet version [12.0.4], but instead [12.0.5]. Try opening the character sheet or running !shaped-update-character to update it.

I've opened the sheet and even tried to run `!shaped-update-character`, but no luck.

I can't run any commands on the token :(

**Comment by symposion** [comment]
Is this unique to one specific token? If so, could you go into the attributes tab and check if it has two version attributes somehow?

**Comment by mlenser** [comment]
I saw it on multiple PCs. I'll check

**Comment by mlenser** [comment]
This has magically resolved itself after waiting a few days. I'm unsure what caused it, but since I can't reproduce it now I'll close this.
