### ISSUE TITLE
Ammo qty renamed to "uses"

### ISSUE THREAD

**Issue by mlenser** [symposion/roll20-shaped-scripts#489]
Can you update the automatic ammo reduction to use "uses" instead of qty? This will be part of 14.0.0.

**Comment by johnfsg** [comment]
I am not sure I follow what you mean, the ammo under edit does show "uses" and not "qty" under the weapon in question and edit it shows arrow and per use. Qty as far as I see on the sheet under edit does not have Qty. I am not a coder so not sure I I just don't understand what you are trying to tell me what to do.

**Comment by mlenser** [comment]
There is nothing you can do. The script needs to update to support 14.x.x.

**Comment by johnfsg** [comment]
Oh ok, so sorry. So there will be another script coming out beyond 10.0.1 which I have loaded? If so I should just wait for it is what your saying.

**Comment by johnfsg** [comment]
So there will be another script coming out beyond 10.0.1 which I have loaded?
