### ISSUE TITLE
Spell uses

### ISSUE THREAD

**Issue by mlenser** [symposion/roll20-shaped-scripts#490]
I've implemented spell uses in the standard way for 14.0.0. I send the typical `{{uses=@{uses}}}`, `{{uses_max=@{uses|max}}}`, `{{per_use=@{per_use}}}`, and `{{repeating_item=${repString}}}`.

Can you add support for it on the script's side?

**Comment by yorickdowne** [comment]
It counts down uses, but also counts down slots at the same time. I take it that's not desired? Should count down use but not a slot?

**Comment by mlenser** [comment]
If uses exist for a spell it should prioritize those over spell slots. So detect if a use exists, if it does then deduct that, otherwise try to use a slot.

**Comment by thorsteneb** [comment]
I'm assuming if the spell is being cast above its level, don't deduct a use, use a slot instead?

This is partially working. Use recovery on spells isn't working yet, and right now it will still deduct uses even when casting at higher level.

**Comment by mlenser** [comment]
Higher level should not use a slot, correct

**Comment by mlenser** [comment]
moved to https://bitbucket.org/mlenser/5eshapedscript/issues/2/spell-uses
