### ISSUE TITLE
Uses deduction seems to require uses_max

### ISSUE THREAD

**Issue by mlenser** [symposion/roll20-shaped-scripts#495]
`uses` can (now) be used without `uses_max` existing. It seems like there is a check to ensure that `uses_max` exists before reducing the `uses`. I've tested that it works when `uses_max` exists, but not otherwise.

**Comment by yorickdowne** [comment]
I found where this is at. How'd you test, so I can test in my campaign? Just create something with uses, no max, and see whether the script will count it down correctly?

**Comment by yorickdowne** [comment]
Looks resolved in my testing. I changed it to key on 'current' instead of 'max'.

**Comment by mlenser** [comment]
Resolved as part of 11.0.0
