### ISSUE TITLE
Suggestion: Move houserules to a sub property of newCharSettings

### ISSUE THREAD

**Issue by Brunhine** [symposion/roll20-shaped-scripts#58]
I propose we move the 'houserules' into a seperate property of newCharSettings.

In addition to some modularization, this will help me condense the UI.

I propose the following change from:
```
  newCharSettings: {
    sheetOutput: '@{output_to_all}',
    ...snip...
    showTargetName: '@{attacks_vs_target_name_no}',
    autoAmmo: '@{ammo_auto_use_var}',
    savingThrowsHalfProf: false,
    mediumArmorMaxDex: 2,
  },
```
to
```
  newCharSettings: {
    sheetOutput: '@{output_to_all}',
    ...snip...
    showTargetName: '@{attacks_vs_target_name_no}',
    autoAmmo: '@{ammo_auto_use_var}',
    houserules: {
      savingThrowsHalfProf: false,
      mediumArmorMaxDex: 2,
    },
  },
```

Also, these settings should be false or RAW by default.

**Comment by symposion** [comment]
Oh man, I can't believe I made that 'true' by default! That was *never* the intention! For all the code quality stuff I'm still being way too careless with all of this!

Agreed about all your changes.
