### ISSUE TITLE
token defaults shouldn't require token to be linked to a character

### ISSUE THREAD

**Issue by symposion** [symposion/roll20-shaped-scripts#6]
_From @symposion on April 13, 2016 15:38_

_Copied from original issue: symposion/roll20-api-scripts#78_

**Comment by symposion** [comment]
_From @Brunhine on April 14, 2016 3:8_

Is the intent here that anything dropped on the object/token layer applied the users token settings? 

If so, this should be doable for most of the token options except for (off the top of my head) 
- bar values (visibility would be fine) 
- name numbering

**Comment by symposion** [comment]
No, there's !shaped-token-defaults which is what this issue is referring to rather obtusely. I just noticed the other day that it fails quietly and mysteriously if you have a token selected but that token doesn't represent a character.

Bar values obviously can't be set, you are right. Name numbering should be fine - you just need to append %%NUMBERED%% to the end of the existing name. Obviously there's no guarantee that the name is correct for the character but that's a separate problem

**Comment by symposion** [comment]
I have decided that i don't want to make this work for un-linked tokens. There's no real use case for it and it makes the code more complex. I've introduced an error message so that there's meaningful feedback when you try and do token-defaults on a non-character token.

**Comment by Brunhine** [comment]
I fully support this decision.
