### ISSUE TITLE
Spell Importer: Duplicate text being imported.

### ISSUE THREAD

**Issue by liquidsonic** [symposion/roll20-shaped-scripts#84]
Spells seem to be importing their descriptive text twice. Not sure why, example when I run !shaped-import-spell --Fireball

It will show the descriptive text as

> A bright streak flashes from your pointing finger to a point you choose within range and then blossoms with a low roar into an explosion of flame. Each creature in a 20-foot-radius sphere centered on that point must make a Dexterity saving throw. A target takes 8d6 fire damage on a failed save, or half as much damage on a successful one.
> The fire spreads around corners. It ignites flammable objects in the area that aren't being worn or carried.
> A bright streak flashes from your pointing finger to a point you choose within range and then blossoms with a low roar into an explosion of flame. Each creature in a 20-foot-radius sphere centered on that point must make a Dexterity saving throw. A target takes 8d6 fire damage on a failed save, or half as much damage on a successful one.
> The fire spreads around corners. It ignites flammable objects in the area that aren't being worn or carried.
> When you cast this spell using a spell slot of 4th level or higher, the damage increases by 1d6 for each slot level above 3rd.

Basically repeating itself twice. Everything else seems fine and dandy. I'm not sure if this is my user error or the script, perhaps you could give me a few ideas. I'll try backtracking to an older version of the script later.

**Comment by beeke01** [comment]
I can confirm this behavior, tested with various spells using the latest sheet (2.5), latest data (0.2.1), and latest version of the script (1.3.4).

**Comment by symposion** [comment]
Yep, this was a bug introduced when I moved to es6 a little while back. Fix coming shortly.
